version: '3'
services:
    # RabbitMQ
    rabbit:
        hostname: rabbit
        image: rabbitmq:3.12.5
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            - "5672:5672"
            - "15672:15672"

    # Django
    web:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        command: ./run_web.sh
        volumes:
            - .:/code:Z
        ports:
            - "8000:8000"
        links:
            - rabbit

    # Celery worker
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./run_celery.sh
        volumes:
            - .:/code:Z
        links:
            - rabbit
        depends_on:
            - rabbit